services:
  web:
    container_name: sc2025-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: development
    ports:
      - "3025:3025"
    env_file:
      - .env
    environment:
      HOSTNAME: 0.0.0.0
    command: ["node", "server.js"]
